### ISSUE TITLE
Localdatabase not updating

### ISSUE THREAD

**Issue by tenjaa** [uncleashi/find-client-android#1]
Hey,
the local database is not updating, when I delete some locations on ml.internalpositioning.
Furthermore, if i want to rescan a location, the location will be displayed two times (same name).

And I needed to see the detailed propabilities for the locations. So I modded the tracking fragment a little bit and updated okhttp because of Android Studio complaining.
If you're interested, I can create a pull request.

**Comment by izach** [comment]
Hi Tenja!

I am interested in your changes.
Can you please show me your changes?

Thanks

**Comment by tenjaa** [comment]
I only needed them for some testing so it's possible that I deleted them. 
I'm on vacations right now so just ping me in about two weeks again if I forget it. I'll take a look when I'm back :)
